#!/bin/sh -xeu

project="$1"
repo="$2"
packages="$3"
sproject="$4"
testreq_packages="$5"

if [ -x /usr/bin/apt-get -a -d /etc/apt/sources.list.d/ ] ; then
# Ubuntu
   srclist="/etc/apt/sources.list.d/Tools.list"
   [ -n "$project" ] && echo "deb http://download.otctools.jf.intel.com/home:/tester:/$project/$repo/ /" >  $srclist
   [ -n "$sproject" ] && echo "deb http://download.otctools.jf.intel.com/$sproject/$repo/ /" >> $srclist
   apt-get update
   apt-get upgrade -y --force-yes
   if [ -n "$testreq_packages" ]; then
     echo "======= Installing TEST REQ packages ========"
     apt-get install -y --force-yes $testreq_packages
   fi
   if [ -n "$packages" ]; then
     echo "======= Installing UNDER TEST packages ========"
     apt-get install -y --force-yes $packages
   fi
elif [ -x /usr/bin/zypper -a -d /etc/zypp/repos.d ] ; then
# OpenSuse
   [ -n "$project" ] && zypper ar -fG http://download.otctools.jf.intel.com/home:/tester:/$project/$repo/ $project
   reponame="tools-`echo \"$sproject\" | tr -d '[:punct:][:space:]'`"
   [ -n "$sproject" ] && zypper ar -fG http://download.otctools.jf.intel.com/$sproject/$repo/ $reponame
   zypper --non-interactive ref
   zypper --non-interactive up
   if [ -n "$testreq_packages" ]; then
     echo "======= Installing TEST REQ packages ========"
     zypper --non-interactive install $testreq_packages
   fi
   if [ -n "$packages" ]; then
     echo "======= Installing UNDER TEST packages ========"
     zypper --non-interactive install $packages
   fi
elif [ \( -x /bin/yum -o -x /usr/bin/yum \) -a -d /etc/yum.repos.d ] ; then
# Fedora
   srclist="/etc/yum.repos.d/otctools.repo"
   [ -n "$project" ] && cat > $srclist <<EOF
[$project]
name=$project
baseurl=http://download.otctools.jf.intel.com/home:/tester:/$project/$repo/
enabled=1
proxy=_none_
gpgcheck=0
EOF

[ -n "$sproject" ] && cat >> $srclist <<EOF
[tools]
name=tools
baseurl=http://download.otctools.jf.intel.com/$sproject/$repo/
enabled=1
proxy=_none_
gpgcheck=0
EOF
   yum -y clean all
   yum -y update
   if [ -n "$testreq_packages" ]; then
     echo "======= Installing TEST REQ packages ========"
     yum -y install $testreq_packages
   fi
   if [ -n "$packages" ]; then
     echo "======= Installing UNDER TEST packages ========"
     yum -y install $packages
   fi
fi
