#!/bin/sh -xeu

create_rpm_repo() {
 reponame=$1
 url=$2

 repofile="/etc/yum.repos.d/$reponame.repo"
 cat > $repofile <<EOF
[$reponame]
name=$reponame
baseurl=$url
enabled=1
proxy=_none_
gpgcheck=0
EOF
}

install_pkgs() {
 cmd=$1
 testreq_pkgs=$2
 pkgs=$3

 if [ -n "$testreq_pkgs" ]; then
   echo "======= Installing TEST REQ packages ========"
   $cmd $testreq_pkgs
 fi
 if [ -n "$pkgs" ]; then
   echo "======= Installing UNDER TEST packages ========"
   $cmd $pkgs
 fi
}

add_extra_repos() {
 r_on=$1
 e_repos=$2
 rlist=$3

 OLDIFS=$IFS
 IFS=','
 for r in ${e_repos}; do
   echo "======= Adding EXTRA repository ========"
   reponame=`echo $r | sed 's/ //g' | sed 's/http://g' | tr -d '[:punct:][:space:]'`
   if [ $r_on = "ubuntu" ] ; then
     echo "$r" >>  $rlist
   elif [ $r_on = "opensuse" ] ; then
     zypper ar -fG "$r" "$reponame"
   elif [ $r_on = "fedora" ] ; then
     create_rpm_repo $reponame $r
   fi
 done
 IFS=$OLDIFS
}

project="$1"
repo="$2"
packages="$3"
sproject="$4"
testreq_packages="$5"
extra_repos="$6"
noupd="$7"

if [ -x /usr/bin/apt-get -a -d /etc/apt/sources.list.d/ ] ; then
# Ubuntu
   run_on="ubuntu"
   srclist="/etc/apt/sources.list.d/Tools.list"
   [ -n "$project" ] && echo "deb http://download.otctools.jf.intel.com/home:/tester:/$project/$repo/ /" >  $srclist
   [ -n "$sproject" ] && echo "deb http://download.otctools.jf.intel.com/$sproject/$repo/ /" >> $srclist
   [ -n "$extra_repos" ] && add_extra_repos $run_on "$extra_repos" $srclist
   apt-get update
   [ "$noupd" != "noupdate" ] && apt-get upgrade -y --force-yes
   install_pkgs "apt-get install -y --force-yes" "$testreq_packages" "$packages"
elif [ -x /usr/bin/zypper -a -d /etc/zypp/repos.d ] ; then
# OpenSuse
   run_on="opensuse"
   [ -n "$project" ] && zypper ar -fG http://download.otctools.jf.intel.com/home:/tester:/$project/$repo/ $project
   reponame="tools-`echo \"$sproject\" | tr -d '[:punct:][:space:]'`"
   [ -n "$sproject" ] && zypper ar -fG http://download.otctools.jf.intel.com/$sproject/$repo/ $reponame
   [ -n "$extra_repos" ] && add_extra_repos $run_on "$extra_repos" ""
   zypper --non-interactive ref
   [ "$noupd" != "noupdate" ] && zypper --non-interactive up
   install_pkgs "zypper --non-interactive install" "$testreq_packages" "$packages"
elif [ \( -x /bin/yum -o -x /usr/bin/yum \) -a -d /etc/yum.repos.d ] ; then
# Fedora
   run_on="fedora"
   srclist="/etc/yum.repos.d/otctools.repo"
   url="http://download.otctools.jf.intel.com/home:/tester:/$project/$repo/"
   [ -n "$project" ] && create_rpm_repo $project $url
   url="http://download.otctools.jf.intel.com/$sproject/$repo/"
   [ -n "$sproject" ] && create_rpm_repo "tools" $url
   [ -n "$extra_repos" ] && add_extra_repos $run_on "$extra_repos" ""
   yum -y clean all
   [ "$noupd" != "noupdate" ] && yum -y update
   install_pkgs "yum -y install" "$testreq_packages" "$packages"
fi
