#!/bin/sh -xefu

src="$1"
reports_dir="$2"

# Run pylint
mkdir -p ~/.pylint.d/
rm -f $reports_dir/pylint.log
export PYTHONPATH=$src
for path in `find $src -name \*.py`; do
    pylint --output-format=parseable --reports=y $path >> $reports_dir/pylint.log
done || :

cd $src
if [ -d tests ] ; then
    # Run nosetests with coverage support
    nosetests -v --with-coverage --with-xunit

    # Run coverage
    coverage=$(which coverage || which python-coverage)
    $coverage xml
fi

# Move reports
for fn in nosetests.xml coverage.xml ; do
    [ -f "$fn" ] && mv $fn $reports_dir
done

echo 'Done'
